import 'package:msp_app/shared/entities/project.dart';
import 'package:msp_app/shared/entities/milestone.dart';
import 'package:msp_app/shared/entities/task.dart';
import 'package:msp_app/shared/entities/meeting.dart';
import 'meeting_mock_data.dart';

class ProjectMockData {
  static List<Project> getProjects() {
    final now = DateTime.now();
    
    return [
      Project(
        id: '1',
        name: 'E-Commerce Platform',
        description: 'Full-stack e-commerce platform with payment integration, inventory management, and customer analytics.',
        status: 'Ongoing',
        priority: 'High',
        timeline: '6 months',
        projectManager: 'Sarah Johnson',
        progress: 65,
        startDate: now.subtract(const Duration(days: 90)),
        endDate: now.add(const Duration(days: 90)),
        icon: 'shopping_cart',
        color: 'FF5E13',
        milestones: [
          Milestone(
            id: 'm1',
            title: 'Project Setup & Planning',
            description: 'Initial project setup, team formation, and detailed planning phase.',
            status: 'Completed',
            startDate: now.subtract(const Duration(days: 90)),
            dueDate: now.subtract(const Duration(days: 75)),
            progress: 100,
            priority: 'High',
            color: 'FF5E13',
            tasks: [
              Task(
                id: 't1',
                title: 'Project Charter Creation',
                description: 'Create comprehensive project charter with scope, objectives, and timeline.',
                status: 'Completed',
                priority: 'High',
                startDate: now.subtract(const Duration(days: 90)),
                dueDate: now.subtract(const Duration(days: 85)),
                assigneeId: 'user1',
                assigneeName: 'John Doe',
                assigneeEmail: 'john.doe@company.com',
                assigneeAvatar: 'https://via.placeholder.com/40',
                color: 'FF5E13',
                estimatedHours: 16,
                actualHours: 18,
              ),
              Task(
                id: 't2',
                title: 'Team Formation',
                description: 'Assemble development team and assign roles.',
                status: 'Completed',
                priority: 'Medium',
                startDate: now.subtract(const Duration(days: 88)),
                dueDate: now.subtract(const Duration(days: 80)),
                assigneeId: 'user2',
                assigneeName: 'Sarah Johnson',
                assigneeEmail: 'sarah.johnson@company.com',
                assigneeAvatar: 'https://via.placeholder.com/40',
                color: 'FFA463',
                estimatedHours: 8,
                actualHours: 8,
              ),
            ],
          ),
          Milestone(
            id: 'm2',
            title: 'Backend Development',
            description: 'Core backend services, database design, and API development.',
            status: 'In Progress',
            startDate: now.subtract(const Duration(days: 75)),
            dueDate: now.subtract(const Duration(days: 30)),
            progress: 80,
            priority: 'High',
            color: 'FFA463',
            tasks: [
              Task(
                id: 't3',
                title: 'Database Schema Design',
                description: 'Design and implement database schema for e-commerce platform.',
                status: 'Completed',
                priority: 'High',
                startDate: now.subtract(const Duration(days: 75)),
                dueDate: now.subtract(const Duration(days: 65)),
                assigneeId: 'user3',
                assigneeName: 'Mike Chen',
                assigneeEmail: 'mike.chen@company.com',
                assigneeAvatar: 'https://via.placeholder.com/40',
                color: 'FF5E13',
                estimatedHours: 24,
                actualHours: 26,
              ),
              Task(
                id: 't4',
                title: 'User Authentication API',
                description: 'Implement secure user authentication and authorization system.',
                status: 'In Progress',
                priority: 'High',
                startDate: now.subtract(const Duration(days: 60)),
                dueDate: now.subtract(const Duration(days: 45)),
                assigneeId: 'user4',
                assigneeName: 'Emily Davis',
                assigneeEmail: 'emily.davis@company.com',
                assigneeAvatar: 'https://via.placeholder.com/40',
                color: 'FF5E13',
                estimatedHours: 32,
                actualHours: 20,
              ),
              Task(
                id: 't5',
                title: 'Product Management API',
                description: 'Develop APIs for product catalog, inventory, and pricing.',
                status: 'Pending',
                priority: 'Medium',
                startDate: now.subtract(const Duration(days: 40)),
                dueDate: now.subtract(const Duration(days: 25)),
                assigneeId: 'user5',
                assigneeName: 'Alex Rodriguez',
                assigneeEmail: 'alex.rodriguez@company.com',
                assigneeAvatar: 'https://via.placeholder.com/40',
                color: 'FFA463',
                estimatedHours: 28,
                actualHours: 0,
              ),
            ],
          ),
          Milestone(
            id: 'm3',
            title: 'Frontend Development',
            description: 'User interface development, responsive design, and user experience optimization.',
            status: 'Planning',
            startDate: now.subtract(const Duration(days: 30)),
            dueDate: now.add(const Duration(days: 30)),
            progress: 20,
            priority: 'High',
            color: 'FFDBBD',
            tasks: [
              Task(
                id: 't6',
                title: 'UI/UX Design',
                description: 'Create comprehensive UI/UX designs for all user interfaces.',
                status: 'In Progress',
                priority: 'High',
                startDate: now.subtract(const Duration(days: 30)),
                dueDate: now.subtract(const Duration(days: 15)),
                assigneeId: 'user6',
                assigneeName: 'Lisa Wang',
                assigneeEmail: 'lisa.wang@company.com',
                assigneeAvatar: 'https://via.placeholder.com/40',
                color: 'FF5E13',
                estimatedHours: 40,
                actualHours: 15,
              ),
              Task(
                id: 't7',
                title: 'React Components Development',
                description: 'Develop reusable React components for the frontend.',
                status: 'Pending',
                priority: 'Medium',
                startDate: now.subtract(const Duration(days: 15)),
                dueDate: now.add(const Duration(days: 15)),
                assigneeId: 'user7',
                assigneeName: 'David Kim',
                assigneeEmail: 'david.kim@company.com',
                assigneeAvatar: 'https://via.placeholder.com/40',
                color: 'FFA463',
                estimatedHours: 48,
                actualHours: 0,
              ),
            ],
          ),
        ],
        meetings: MeetingMockData.getMeetings(),
      ),
      Project(
        id: '2',
        name: 'Mobile Banking App',
        description: 'Secure mobile banking application with biometric authentication and real-time transactions.',
        status: 'Planning',
        priority: 'High',
        timeline: '4 months',
        projectManager: 'Michael Brown',
        progress: 15,
        startDate: now.subtract(const Duration(days: 30)),
        endDate: now.add(const Duration(days: 90)),
        icon: 'account_balance',
        color: '4CAF50',
        milestones: [
          Milestone(
            id: 'm4',
            title: 'Security & Compliance',
            description: 'Implement security measures and ensure regulatory compliance.',
            status: 'Planning',
            startDate: now.subtract(const Duration(days: 30)),
            dueDate: now.add(const Duration(days: 15)),
            progress: 10,
            priority: 'High',
            color: '4CAF50',
            tasks: [
              Task(
                id: 't8',
                title: 'Security Audit',
                description: 'Conduct comprehensive security audit and vulnerability assessment.',
                status: 'Pending',
                priority: 'High',
                startDate: now.subtract(const Duration(days: 30)),
                dueDate: now.subtract(const Duration(days: 15)),
                assigneeId: 'user8',
                assigneeName: 'Security Team',
                assigneeEmail: 'security@company.com',
                assigneeAvatar: 'https://via.placeholder.com/40',
                color: '4CAF50',
                estimatedHours: 20,
                actualHours: 0,
              ),
            ],
          ),
        ],
        meetings: [], // No meetings for this project
      ),
      Project(
        id: '3',
        name: 'AI Chatbot Integration',
        description: 'Intelligent customer service chatbot with natural language processing capabilities.',
        status: 'Completed',
        priority: 'Medium',
        timeline: '3 months',
        projectManager: 'Jennifer Lee',
        progress: 100,
        startDate: now.subtract(const Duration(days: 120)),
        endDate: now.subtract(const Duration(days: 30)),
        icon: 'smart_toy',
        color: '9C27B0',
        milestones: [
          Milestone(
            id: 'm5',
            title: 'AI Model Training',
            description: 'Train and optimize AI models for natural language understanding.',
            status: 'Completed',
            startDate: now.subtract(const Duration(days: 120)),
            dueDate: now.subtract(const Duration(days: 90)),
            progress: 100,
            priority: 'High',
            color: '9C27B0',
            tasks: [
              Task(
                id: 't9',
                title: 'Data Collection & Preprocessing',
                description: 'Collect and preprocess training data for the AI model.',
                status: 'Completed',
                priority: 'High',
                startDate: now.subtract(const Duration(days: 120)),
                dueDate: now.subtract(const Duration(days: 105)),
                assigneeId: 'user9',
                assigneeName: 'AI Team',
                assigneeEmail: 'ai@company.com',
                assigneeAvatar: 'https://via.placeholder.com/40',
                color: '9C27B0',
                estimatedHours: 32,
                actualHours: 35,
              ),
            ],
          ),
        ],
        meetings: [], // No meetings for this project
      ),
    ];
  }
}
