import '../entities/task.dart';

/// Mock data cho Task entity
class TaskMockData {
  static List<Task> getTasks() {
    return [
      Task(
        id: 'task_001',
        title: 'Thiết kế giao diện đăng nhập',
        description: 'Tạo giao diện đăng nhập với validation và responsive design',
        status: 'In Progress',
        priority: 'High',
        startDate: DateTime.now().subtract(const Duration(days: 5)),
        dueDate: DateTime.now().add(const Duration(days: 3)),
        assigneeId: 'user_001',
        assigneeName: 'Nguyễn Văn A',
        assigneeEmail: 'nguyenvana@example.com',
        assigneeAvatar: '👨‍💻',
        color: '#FF9800',
        projectName: 'Website Redesign',
        estimatedHours: 8,
        actualHours: 5,
      ),
      Task(
        id: 'task_002',
        title: 'Fix bug đăng ký tài khoản',
        description: 'Sửa lỗi validation email và xử lý trường hợp trùng lặp',
        status: 'Completed',
        priority: 'High',
        startDate: DateTime.now().subtract(const Duration(days: 7)),
        dueDate: DateTime.now().subtract(const Duration(days: 1)),
        assigneeId: 'user_002',
        assigneeName: 'Trần Thị B',
        assigneeEmail: 'tranthib@example.com',
        assigneeAvatar: '👩‍💻',
        color: '#4CAF50',
        projectName: 'Mobile App Development',
        estimatedHours: 6,
        actualHours: 6,
      ),
      Task(
        id: 'task_003',
        title: 'Viết API documentation',
        description: 'Tạo tài liệu API cho các endpoint mới',
        status: 'Todo',
        priority: 'Medium',
        startDate: DateTime.now().add(const Duration(days: 1)),
        dueDate: DateTime.now().add(const Duration(days: 7)),
        assigneeId: 'user_003',
        assigneeName: 'Lê Văn C',
        assigneeEmail: 'levanc@example.com',
        assigneeAvatar: '👨‍🔬',
        color: '#2196F3',
        projectName: 'API Development',
        estimatedHours: 12,
        actualHours: 0,
      ),
      Task(
        id: 'task_004',
        title: 'Code review cho module payment',
        description: 'Review code và đưa ra feedback cho module thanh toán',
        status: 'In Progress',
        priority: 'Medium',
        startDate: DateTime.now().subtract(const Duration(days: 2)),
        dueDate: DateTime.now().add(const Duration(days: 2)),
        assigneeId: 'user_004',
        assigneeName: 'Phạm Thị D',
        assigneeEmail: 'phamthid@example.com',
        assigneeAvatar: '👩‍🔧',
        color: '#9C27B0',
        projectName: 'E-commerce Platform',
        estimatedHours: 4,
        actualHours: 2,
      ),
      Task(
        id: 'task_005',
        title: 'Setup CI/CD pipeline',
        description: 'Cấu hình pipeline tự động build và deploy',
        status: 'On Hold',
        priority: 'Low',
        startDate: DateTime.now().subtract(const Duration(days: 10)),
        dueDate: DateTime.now().add(const Duration(days: 5)),
        assigneeId: 'user_005',
        assigneeName: 'Hoàng Văn E',
        assigneeEmail: 'hoangvane@example.com',
        assigneeAvatar: '👨‍⚙️',
        color: '#FF5722',
        projectName: 'DevOps Setup',
        estimatedHours: 16,
        actualHours: 8,
      ),
      Task(
        id: 'task_006',
        title: 'Thiết kế database schema',
        description: 'Thiết kế cấu trúc database cho hệ thống quản lý dự án',
        status: 'Completed',
        priority: 'High',
        startDate: DateTime.now().subtract(const Duration(days: 15)),
        dueDate: DateTime.now().subtract(const Duration(days: 5)),
        assigneeId: 'user_006',
        assigneeName: 'Vũ Thị F',
        assigneeEmail: 'vuthif@example.com',
        assigneeAvatar: '👩‍💼',
        color: '#607D8B',
        projectName: 'Database Design',
        estimatedHours: 20,
        actualHours: 18,
      ),
      Task(
        id: 'task_007',
        title: 'Implement user authentication',
        description: 'Xây dựng hệ thống xác thực người dùng với JWT',
        status: 'In Progress',
        priority: 'High',
        startDate: DateTime.now().subtract(const Duration(days: 3)),
        dueDate: DateTime.now().add(const Duration(days: 4)),
        assigneeId: 'user_007',
        assigneeName: 'Đặng Văn G',
        assigneeEmail: 'dangvang@example.com',
        assigneeAvatar: '👨‍🔐',
        color: '#795548',
        projectName: 'Security Module',
        estimatedHours: 10,
        actualHours: 6,
      ),
      Task(
        id: 'task_008',
        title: 'Viết unit tests cho API',
        description: 'Tạo unit tests cho các API endpoints',
        status: 'Todo',
        priority: 'Medium',
        startDate: DateTime.now().add(const Duration(days: 2)),
        dueDate: DateTime.now().add(const Duration(days: 10)),
        assigneeId: 'user_008',
        assigneeName: 'Bùi Thị H',
        assigneeEmail: 'buithih@example.com',
        assigneeAvatar: '👩‍🧪',
        color: '#E91E63',
        projectName: 'Testing Framework',
        estimatedHours: 14,
        actualHours: 0,
      ),
      Task(
        id: 'task_009',
        title: 'Optimize database queries',
        description: 'Tối ưu hóa các truy vấn database để cải thiện performance',
        status: 'In Progress',
        priority: 'Medium',
        startDate: DateTime.now().subtract(const Duration(days: 1)),
        dueDate: DateTime.now().add(const Duration(days: 6)),
        assigneeId: 'user_009',
        assigneeName: 'Ngô Văn I',
        assigneeEmail: 'ngovani@example.com',
        assigneeAvatar: '👨‍⚡',
        color: '#3F51B5',
        projectName: 'Performance Optimization',
        estimatedHours: 8,
        actualHours: 3,
      ),
      Task(
        id: 'task_010',
        title: 'Deploy ứng dụng lên production',
        description: 'Triển khai ứng dụng lên môi trường production',
        status: 'Todo',
        priority: 'High',
        startDate: DateTime.now().add(const Duration(days: 5)),
        dueDate: DateTime.now().add(const Duration(days: 7)),
        assigneeId: 'user_010',
        assigneeName: 'Lý Thị K',
        assigneeEmail: 'lythik@example.com',
        assigneeAvatar: '👩‍🚀',
        color: '#FF9800',
        projectName: 'Production Deployment',
        estimatedHours: 6,
        actualHours: 0,
      ),
    ];
  }
}
