name: msp_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # Riverpod
  flutter_riverpod: ^2.5.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # Network & HTTP
  http: ^1.5.0
  
  # Dependency Injection
  get_it: ^8.0.0
  
  # Storage
  shared_preferences: ^2.3.2
  
  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Permissions
  permission_handler:  ^12.0.1

  # jwt decoder
  jwt_decoder: ^2.0.1
  
  # Stream Video
  stream_video: 0.11.0
  stream_video_flutter: 0.11.0
  stream_video_push_notification: 0.11.0

  # Marquee
  marquee: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
